// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbGzitwjn2zg4yNwSFf8GUZwXfYwrQhEA',
    appId: '1:383611394485:web:7bd6c4b5d9152551c4e1fc',
    messagingSenderId: '383611394485',
    projectId: 'deepshield-d615f',
    authDomain: 'deepshield-d615f.firebaseapp.com',
    storageBucket: 'deepshield-d615f.firebasestorage.app',
    measurementId: 'G-L84G7KE7LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFdF_Zg8GpWB2XA0azPtleYkj7Kie_ws',
    appId: '1:383611394485:android:3a102138e6a39189c4e1fc',
    messagingSenderId: '383611394485',
    projectId: 'deepshield-d615f',
    storageBucket: 'deepshield-d615f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeYs64xrYM9WkPolbpcGkykffOzGV0iUM',
    appId: '1:383611394485:ios:a63a8d4e2b8a5490c4e1fc',
    messagingSenderId: '383611394485',
    projectId: 'deepshield-d615f',
    storageBucket: 'deepshield-d615f.firebasestorage.app',
    iosBundleId: 'com.example.deepshield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeYs64xrYM9WkPolbpcGkykffOzGV0iUM',
    appId: '1:383611394485:ios:a63a8d4e2b8a5490c4e1fc',
    messagingSenderId: '383611394485',
    projectId: 'deepshield-d615f',
    storageBucket: 'deepshield-d615f.firebasestorage.app',
    iosBundleId: 'com.example.deepshield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbGzitwjn2zg4yNwSFf8GUZwXfYwrQhEA',
    appId: '1:383611394485:web:df72b47601e3e76cc4e1fc',
    messagingSenderId: '383611394485',
    projectId: 'deepshield-d615f',
    authDomain: 'deepshield-d615f.firebaseapp.com',
    storageBucket: 'deepshield-d615f.firebasestorage.app',
    measurementId: 'G-JB7910S9WR',
  );
}
